config/routes.rb
Rails.application.routes.draw do
  
	namespace :api, format: 'json' do
		namespace :v1 do
			resources :clients
			resources :projects
		end
	end
	get 'instructors/check_name_present'
	get 'instructors/check_email_present'
	resources :cities
  resources :courses
  resources :instructors
  resources :students

  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
	has_many :courses
	validates_presence_of :name, :email, :bio
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.paginate(:page => params[:page], :per_page => 5)
    @instructor = Instructor.new
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # PssOST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to instructors_path, notice: 'Instructor was successfully updated.' }
        format.json { render :index, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_name_present
    @instructor = Instructor.find_by(name: params[:name])
    render json: @instructor.nil? ? {'msg': 'can be used'} : {'msg': 'already taken'}   
  end

  def check_email_present
    @instructor = Instructor.find_by(email: params[:email])
    render json: @instructor.nil? ? {'msg': 'can be used'} : {'msg': 'already taken'}   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name, :email, :bio)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(instructor,remote: true, local: true, id:'form') do |form| %>
<% if instructor.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

  <ul>
    <% instructor.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group" id="nameGroup">
  <%= form.label :name %>
  <%= form.text_field :name, id: :instructor_name, class: "form-control" %>
  <span id="nameError"></span>
</div>

<div class="form-group" id="emailGroup">
  <%= form.label :email %>
  <%= form.text_field :email, id: :instructor_email, class: "form-control" %>
  <span id="emailError"></span>
</div>

<div class="form-group">
  <%= form.label :bio %>
  <%= form.text_area :bio, id: :instructor_bio, class: "form-control" %>
</div>

<h4>Select Courses</h4>
<%= form.collection_check_boxes :course_ids, Course.all, :id, :name do |course| %>
<%= course.check_box %>
<%= course.label %>
<% end %>

<div class="actions">
  <%= form.submit "Submit", class: "btn btn-success" %> or
  <a href="#" id="reset">reset</a>
</div>
<% end %>

<script type="text/javascript">
  var formHandle = document.getElementById('form');
  var resetHandle = document.getElementById('reset'); 
  var nameGroupHandle = document.getElementById('nameGroup')
  var emailGroupHandle = document.getElementById('emailGroup')
  var validator = {
    nameValid: false,
    emailValid: false
  }
  var nameFormat = /^(([A-Za-z]+[\-\']?)*([A-Za-z]+)?\s)+([A-Za-z]+[\-\']?)*([A-Za-z]+)?$/;
  var emailFormat = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

  resetHandle.addEventListener('click', function(e){
    e.preventDefault();
    formHandle.reset();
  },false);
  var nameHandle = document.getElementById('instructor_name');
  var nameErrorHandle = document.getElementById('nameError');
// nameHandle.addEventListener('blur', function(){
//   var xhr = new XMLHttpRequest();
//   xhr.open('GET','/instructors/check_name_present?name=' + nameHandle.value, true)
//   xhr.onreadystatechange = function(){
//     if(xhr.readyState === 4 && xhr.status === 200){
//       var response = JSON.parse(xhr.responseText);
//       nameErrorHandle.innerHTML = response.msg;
//     }
//   }
//   xhr.send()
//   }, false);
nameHandle.addEventListener('blur', function(){
  nameValidation();
}, false)
nameHandle.addEventListener('focus', function(){
  nameErrorHandle.innerHTML = "";
},false);

function nameValidation(){
  if(nameHandle.value === ""){
    validator.nameValid = false;
    nameErrorHandle.innerHTML = "Cn't be blank"
    nameGroupHandle.classList.remove('formSuccess')
    nameGroupHandle.classList.add('formError')
  }
  else if(!nameFormat.test(nameHandle)){
    validator.nameValid = false;
    nameErrorHandle.innerHTML = "Only Alphabets Plzz"
    nameGroupHandle.classList.remove('formSuccess')
    nameGroupHandle.classList.add('formError')
  }
  else{
    validator.nameValid = true;
    nameErrorHandle.innerHTML = "Nice"
    nameGroupHandle.classList.remove('formError')
    nameGroupHandle.classList.add('formSuccess')
  }
}

var emailHandle = document.getElementById('instructor_email');
var emailErrorHandle = document.getElementById('emailError');
// emailHandle.addEventListener('blur', function(){
//   var xhr = new XMLHttpRequest();
//   xhr.open('GET','/instructors/check_email_present?email=' + emailHandle.value, true)
//   xhr.onreadystatechange = function(){
//     if(xhr.readyState === 4 && xhr.status === 200){
//       var response = JSON.parse(xhr.responseText);
//       emailErrorHandle.innerHTML = response.msg;
//     }
//   }
//   xhr.send()
//   }, false);
emailHandle.addEventListener('blur', function(){
  emailValidation();
}, false)
emailHandle.addEventListener('focus', function(){
  emailErrorHandle.innerHTML = "";
},false);

function emailValidation(){
  if(emailHandle.value === ""){
    validator.emailValid = false;
    emailErrorHandle.innerHTML = "Cn't be blank"
    emailGroupHandle.classList.remove('formSuccess')
    emailGroupHandle.classList.add('formError')
  }
  else if(emailFormat.test(emailHandle)){
    validator.emailValid = false;
    emailErrorHandle.innerHTML = "Vaild Email Plzz"
    emailGroupHandle.classList.remove('formSuccess')
    emailGroupHandle.classList.add('formError')
  }
  else{
    validator.emailValid = true;
    emailErrorHandle.innerHTML = "Nice"
    emailGroupHandle.classList.remove('formError')
    emailGroupHandle.classList.add('formSuccess')
  }
}
formHandle.addEventListener('submit', function(e){
  nameValidation();
  emailValidation();
  if(Object.values(validator).includes(false)){
    e.preventDefault();
        // setTimeout(function(){
        //   submitHandle.disabled = false;
        // }, 100);
      }
    }, false)
document.querySelector('#reset').addEventListener('click', function(e){
  e.preventDefault();
  formHandle.reset();
  nameErrorHandle.innerHTML = "";
  emailErrorHandle.innerHTML = "";
}, false)


</script>

app/views/instructors/_instructor-edit.html.erb
<%= render 'form', instructor: instructor %>

app/views/instructors/_instructor-info.html.erb
<p>
  <strong>Name:</strong>
  <%=instructor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%=instructor.email %>
</p>

<p>
  <strong>Bio:</strong>
  <%= instructor.bio %>
</p>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-8">
    <h2>Instructors</h2>
    <table class="table table-striped "

    id="instructors_table">
      <thead>
        <tr>
          <th>S No.</th>
          <th>Name</th>
          <th>Email</th>
          <th>Bio</th>
          <th> Actions </th>
        </tr>
      </thead>

      <tbody>
        <% @instructors.each_with_index do |instructor, index| %>
        <tr id=<%= instructor.id %> class="instructors">
          <td><%= index + 1 %></td>
          <td> 
            <button type="button" class="btn btn-link" data-toggle="modal" data-target="#instructor<%=index%>"><%=instructor.name%></button>
            <div class="modal fade" id="instructor<%=index%>" tabindex="-1" role="dialog" aria-labelledby="addBioLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="addBioLabel">Bio</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= render 'instructor-info',instructor: instructor%>
                  </div>
                </div>
              </div>
            </div>
          </td>
          <td><%= instructor.email %></td>
          <td><%= instructor.bio %></td>
          <td><button type="button" class="btn btn-link" data-toggle="modal" data-target="#instructor"><%=link_to 'Edit', instructors_path(instructor)%></button>
            <div class="modal fade" id="instructor" tabindex="-1" role="dialog" aria-labelledby="addBioLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="addBioLabel">Edit Form</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= render 'instructor-edit',instructor: instructor%>
                  </div>
                </div>
              </div>
            </div>| <%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <h3>Add Instructor</h3>
    <%= render 'form', instructor: @instructor %>
  </div>
</div>

<%#= link_to 'New Instructor', new_instructor_path %>
<% data = {}
@instructors.each do |instructor|
  total = 0
  instructor.courses.each do |course|
    total += course.students.count
  end
  data[instructor.name] = total
end
%>
<div class="row">
  <div class="col-md-7">
    <%= bar_chart(data) %>
  </div>
  <div class="col-md-5">
    <%= pie_chart(data) %>
  </div>
</div>
<%= will_paginate(@instructors, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<% if notice %>
<div class="alert alert-success">
	<%= notice %>
</div>
<%end%>

<%= render 'instructor-info',instructor: @instructor%>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>

<script type="text/javascript">
	$.growl.notice({ message: "Successfully created Instructor" });
</script>