config/routes.rb
Rails.application.routes.draw do
  
	namespace :api, format: 'json' do
		namespace :v1 do
			resources :clients
			resources :projects
		end
	end
	get 'instructors/check_name_present'
	get 'instructors/check_email_present'
	resources :cities
  resources :courses
  resources :instructors
  resources :students

  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.paginate(:page => params[:page], :per_page => 3)
    @course = Course.new
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.js
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.js
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to @course, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :instructor_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<!-- <div class="col-md-4", style="padding-bottom: 15px">
      <div class="card">
        <img class="card-img-top" src="http://placeimg.com/286/180/any?t=1519715668565" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%#= @course.name %></h5>
          <p class="card-text"><%#= @course.description.truncate(100)%><%#= link_to "view more", @course %></p>
          <%#= link_to "Enroll", new_student_path, class: "btn btn-primary" %>
        </div>
         <div class="card-footer">
            <small class="text-muted"><%= @course.students.count %> students have already taken course</small>
          </div>
      </div>
</div> -->

app/views/courses/_form.html.erb
<%= form_for(course, remote: true, id: "course_form") do |form| %>
<% if course.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>
  <ul>
    <% course.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :course_name, class: "form-control" %>
  </div>
</div>
<div class="field">
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :course_description, class: "form-control" %>
  </div>
</div>
<div class="field">
  <div class="form-group">
    <%= form.label :instructor_id %>
    <%= form.collection_select :instructor_id, Instructor.all, :id, :name, {prompt: "Select Instructor"}, {class: "form-control"} %>
  </div>
</div>
<div class="actions">
  <%= form.submit "Submit", class: "btn btn-primary" %>
</div>
  <% end %>
  <script type="text/javascript">
    formHandle = document.getElementByID("course_form")
    resetHandle = document.getElementByID('reset')
    resetHandle.addEventListener("click", function(){
      $('#addCourse').modal('show');
      formHandle.reset()
    },false)
  </script>

app/views/courses/create.js.erb
  // $('#errors').html("<%= escape_javascript render 'errors'%>");
  // $('#errors').hide();
  $('#addCourse').modal('hide');
  $('#courseList').prepend("<%= escape_javascript render 'course' %>");

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h2> Listing Courses</h2>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addCourse">
  Add Course
</button>

<!-- Modal -->
<div class="modal fade" id="addCourse" tabindex="-1" role="dialog" aria-labelledby="addCourseLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addCourseLabel">Add a new course</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'form', course: @course %>
      </div>
    </div>
  </div>
</div>
<div class="row", id="courseList">
  <% @courses.each do |course| %>
  <div class="col-md-4", style="padding-bottom: 15px">
    <div class="card">
      <img class="card-img-top" src="http://placeimg.com/286/180/any?t=1519715668565" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= course.name %></h5>
        <p class="card-text"><%= course.description.truncate(100)%><%=link_to "view more", course %></p>
        <%= link_to "Enroll", new_student_path, class: "btn btn-primary" %><%#= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <div class="card-footer">
        <small class="text-muted"><%= course.students.count %> students have already taken course</small>
      </div>
    </div>
  </div>
  <% end %>
</div>
<%= will_paginate(@courses, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Instructor</th>
      <th>Count</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%# @courses.each do |course| %>
      <tr>
        <td><%#= link_to course.name, course %></td>
        <td><%#= course.description %></td>
        <td><%#= course.instructor.name %></td>
        <td><%#= course.students.length %></td>
        <td><%#= link_to 'Edit', edit_course_path(course) %></td>
          <%#= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
    <%# end %>
  </tbody>
</table> -->
<br>
<%#= link_to 'New Course', new_course_path %>
<% data = {} 
@courses.each do |course|
  data[course.name] = course.students.length
end 
%>
<%= data %>
<%= pie_chart(data) %>
<%= column_chart(data) %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<strong>Name:</strong>
	<%= @course.name %>
</p>
<p>
	<strong>Description:</strong>
	<%= @course.description %>
</p>
<p>
	<strong>Instructor:</strong>
	<%= @course.instructor.name %>
</p>
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %> |
<%= link_to 'Destroy', @course, method: :delete, data: { confirm: 'Are you sure?' } %>